net: wireless: fix build not using NDO_CONFIG_SUPPORT
kernel/sony/msm/drivers/net/wireless/bcmdhd/dhd_linux.c:6716:25: error: 'pub' undeclared (first use in this function)

changed in commit 832b9f56493753bd3b927c3f1595d641b6a572dd

Signed-off-by: David Viteri <davidteri91@gmail.com>